server:
   port: 8848

      
spring:
  
  devtools:
    restart:
      enabled: true
  datasource:
    url: "jdbc:mysql://10.120.112.115:3306/loisdashboard?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true"
    username: mysql4lois
    password: mysql4lois
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    maxIdle: 10 
      


  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: html5
    encoding: utf-8
    servlet:
      content-type: text/html